### ISSUE TITLE
Can I use voice signal as the input?

### ISSUE THREAD

**Issue by Joanna1212** [MuSAELab/amplitude-modulation-analysis-module#9]
I want to extract **Modulation Spectral Feature** of voice signal with your code. 
Your data example is the eeg or ecg signal. I try to change the signal from your eeg/ecg data to **voice  signal x** because I think they are similar signals, but there are mistakes when I run the code.
Can you give me some suggestions that how to use your code to process my voice signal?

**Comment by spidim** [comment]
Hi @Joanna1212. I would like to do the same thing. Have you managed to run it after all?

**Comment by rcassani** [comment]
Hi @Joanna1212 and @spidim, a speech example has been added, see https://github.com/MuSAELab/amplitude-modulation-analysis-module/issues/10
